
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/abc
      password: root
      username: root
    #   driver-class-name: com.mysql.jdbc.Driver
    jpa:
    #   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      properties:
         hibernate:
            format_sql: true
      hibernate:
        ddl-auto: create
      show-sql: true
        
